/*
 * This file is generated by jOOQ.
*/
package meta.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailBlacklist implements Serializable {

    private static final long serialVersionUID = -1334261907;

    private final String email;

    public EmailBlacklist(EmailBlacklist value) {
        this.email = value.email;
    }

    public EmailBlacklist(
        String email
    ) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmailBlacklist (");

        sb.append(email);

        sb.append(")");
        return sb.toString();
    }
}
