/*
 * This file is generated by jOOQ.
*/
package meta.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.enums.EventStatus;
import meta.tables.interfaces.IEvent;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements IEvent {

    private static final long serialVersionUID = -415271780;

    private final Long        id;
    private final String      name;
    private final String      sponsor;
    private final String      contact;
    private final Timestamp   date;
    private final String      details;
    private final String      location;
    private final EventStatus status;
    private final Integer     maxParticipants;
    private final Timestamp   registrationOpens;

    public Event(Event value) {
        this.id = value.id;
        this.name = value.name;
        this.sponsor = value.sponsor;
        this.contact = value.contact;
        this.date = value.date;
        this.details = value.details;
        this.location = value.location;
        this.status = value.status;
        this.maxParticipants = value.maxParticipants;
        this.registrationOpens = value.registrationOpens;
    }

    public Event(
        Long        id,
        String      name,
        String      sponsor,
        String      contact,
        Timestamp   date,
        String      details,
        String      location,
        EventStatus status,
        Integer     maxParticipants,
        Timestamp   registrationOpens
    ) {
        this.id = id;
        this.name = name;
        this.sponsor = sponsor;
        this.contact = contact;
        this.date = date;
        this.details = details;
        this.location = location;
        this.status = status;
        this.maxParticipants = maxParticipants;
        this.registrationOpens = registrationOpens;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public String getSponsor() {
        return this.sponsor;
    }

    @Override
    public String getContact() {
        return this.contact;
    }

    @Override
    public Timestamp getDate() {
        return this.date;
    }

    @Override
    public String getDetails() {
        return this.details;
    }

    @Override
    public String getLocation() {
        return this.location;
    }

    @Override
    public EventStatus getStatus() {
        return this.status;
    }

    @Override
    public Integer getMaxParticipants() {
        return this.maxParticipants;
    }

    @Override
    public Timestamp getRegistrationOpens() {
        return this.registrationOpens;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sponsor);
        sb.append(", ").append(contact);
        sb.append(", ").append(date);
        sb.append(", ").append(details);
        sb.append(", ").append(location);
        sb.append(", ").append(status);
        sb.append(", ").append(maxParticipants);
        sb.append(", ").append(registrationOpens);

        sb.append(")");
        return sb.toString();
    }
}
