/*
 * This file is generated by jOOQ.
*/
package meta.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.tables.interfaces.IFlywaySchemaHistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistory implements IFlywaySchemaHistory {

    private static final long serialVersionUID = -442973237;

    private final Integer   installedRank;
    private final String    version;
    private final String    description;
    private final String    type;
    private final String    script;
    private final Integer   checksum;
    private final String    installedBy;
    private final Timestamp installedOn;
    private final Integer   executionTime;
    private final Boolean   success;

    public FlywaySchemaHistory(FlywaySchemaHistory value) {
        this.installedRank = value.installedRank;
        this.version = value.version;
        this.description = value.description;
        this.type = value.type;
        this.script = value.script;
        this.checksum = value.checksum;
        this.installedBy = value.installedBy;
        this.installedOn = value.installedOn;
        this.executionTime = value.executionTime;
        this.success = value.success;
    }

    public FlywaySchemaHistory(
        Integer   installedRank,
        String    version,
        String    description,
        String    type,
        String    script,
        Integer   checksum,
        String    installedBy,
        Timestamp installedOn,
        Integer   executionTime,
        Boolean   success
    ) {
        this.installedRank = installedRank;
        this.version = version;
        this.description = description;
        this.type = type;
        this.script = script;
        this.checksum = checksum;
        this.installedBy = installedBy;
        this.installedOn = installedOn;
        this.executionTime = executionTime;
        this.success = success;
    }

    @Override
    public Integer getInstalledRank() {
        return this.installedRank;
    }

    @Override
    public String getVersion() {
        return this.version;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public String getType() {
        return this.type;
    }

    @Override
    public String getScript() {
        return this.script;
    }

    @Override
    public Integer getChecksum() {
        return this.checksum;
    }

    @Override
    public String getInstalledBy() {
        return this.installedBy;
    }

    @Override
    public Timestamp getInstalledOn() {
        return this.installedOn;
    }

    @Override
    public Integer getExecutionTime() {
        return this.executionTime;
    }

    @Override
    public Boolean getSuccess() {
        return this.success;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FlywaySchemaHistory (");

        sb.append(installedRank);
        sb.append(", ").append(version);
        sb.append(", ").append(description);
        sb.append(", ").append(type);
        sb.append(", ").append(script);
        sb.append(", ").append(checksum);
        sb.append(", ").append(installedBy);
        sb.append(", ").append(installedOn);
        sb.append(", ").append(executionTime);
        sb.append(", ").append(success);

        sb.append(")");
        return sb.toString();
    }
}
