version: '3.7'
services:
  db:
    image: postgres:10.6
    restart: unless-stopped
    ports:
      - "45433:5432"
    networks:
      - backend
    volumes:
      - /opt/postgresql:/var/lib/postgresql
      - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: wds
      POSTGRES_DB: wds_db

  backend:
    restart: unless-stopped
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/wds_db
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "5000:5000"

networks:
  backend:
