-- Init
INSERT INTO "public"."event" ("id", "volume", "name", "sponsor", "contact", "date", "details", "location", "status", "max_participants", "registration_opens") VALUES (DEFAULT, 10, 'koe1', 'Gofore', 'esa', '2018-12-19 09:06:12.595000', 'jotain', 'Tampere', 'OPEN', 2, '2018-12-15');
INSERT INTO "public"."event" ("id", "volume", "name", "sponsor", "contact", "date", "details", "location", "status", "max_participants", "registration_opens") VALUES (DEFAULT, 11, 'toinen', 'Solita', 'pena', '2018-12-19 09:07:03.020000', 'koe', 'Hervanta', 'PLANNING', 2, '2019-02-01');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John1', 'Smith', 'john@smith.com', 'test', '1234', 1000, 1, 'REGISTERED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John2', 'Smith', 'john@smith.com', 'test', '1235', 2000, 1, 'REGISTERED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John3', 'Smith', 'john@smith.com', 'test', '1236', 1000, 2, 'REGISTERED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John4', 'Smith', 'john@smith.com', 'test', '1237', 2000, 2, 'REGISTERED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John5', 'Smith', 'john@smith.com', 'test', '1238', 3000, 2, 'WAIT_LISTED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John6', 'Smith', 'john@smith.com', 'test', '1239', 3000, 1, 'WAIT_LISTED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John7', 'Smith', 'john@smith.com', 'test', '1240', 4000, 1, 'WAIT_LISTED');
INSERT INTO "public"."participant" ("id", "first_name", "last_name", "email", "affiliation", "verification_token", "order_number", "event_id", "status") VALUES (DEFAULT, 'John8', 'Smith', 'john@smith.com', 'test', '1241', 5000, 1, 'WAIT_LISTED');

