/*
 * This file is generated by jOOQ.
 */
package meta.routines;


import javax.annotation.processing.Generated;

import meta.Public;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdateEventStatus extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1455187341;

    /**
     * Create a new routine call instance
     */
    public UpdateEventStatus() {
        super("update_event_status", Public.PUBLIC);
    }
}
