/*
 * This file is generated by jOOQ.
*/
package meta;


import javax.annotation.Generated;

import meta.tables.Event;
import meta.tables.FlywaySchemaHistory;
import meta.tables.Participant;
import meta.tables.records.EventRecord;
import meta.tables.records.FlywaySchemaHistoryRecord;
import meta.tables.records.ParticipantRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EventRecord, Long> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
    public static final Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = Identities0.IDENTITY_PARTICIPANT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> EVENT_PKEY = UniqueKeys0.EVENT_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = UniqueKeys0.PARTICIPANT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ParticipantRecord, EventRecord> PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY = ForeignKeys0.PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<EventRecord, Long> IDENTITY_EVENT = createIdentity(Event.EVENT, Event.EVENT.ID);
        public static Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = createIdentity(Participant.PARTICIPANT, Participant.PARTICIPANT.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EventRecord> EVENT_PKEY = createUniqueKey(Event.EVENT, "event_pkey", Event.EVENT.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = createUniqueKey(Participant.PARTICIPANT, "participant_pkey", Participant.PARTICIPANT.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ParticipantRecord, EventRecord> PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY = createForeignKey(meta.Keys.EVENT_PKEY, Participant.PARTICIPANT, "participant__participant_event_id_fkey", Participant.PARTICIPANT.EVENT_ID);
    }
}
