/*
 * This file is generated by jOOQ.
 */
package meta;


import javax.annotation.processing.Generated;

import meta.tables.Contact;
import meta.tables.Event;
import meta.tables.FlywaySchemaHistory;
import meta.tables.Participant;
import meta.tables.records.ContactRecord;
import meta.tables.records.EventRecord;
import meta.tables.records.FlywaySchemaHistoryRecord;
import meta.tables.records.ParticipantRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ContactRecord, Long> IDENTITY_CONTACT = Identities0.IDENTITY_CONTACT;
    public static final Identity<EventRecord, Long> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
    public static final Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = Identities0.IDENTITY_PARTICIPANT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContactRecord> CONTACT_PKEY = UniqueKeys0.CONTACT_PKEY;
    public static final UniqueKey<ContactRecord> CONTACT_EMAIL_KEY = UniqueKeys0.CONTACT_EMAIL_KEY;
    public static final UniqueKey<EventRecord> EVENT_PKEY = UniqueKeys0.EVENT_PKEY;
    public static final UniqueKey<EventRecord> EVENT_VOLUME_KEY = UniqueKeys0.EVENT_VOLUME_KEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = UniqueKeys0.PARTICIPANT_PKEY;
    public static final UniqueKey<ParticipantRecord> PARTICIPANT_VERIFICATION_TOKEN_UNIQUE = UniqueKeys0.PARTICIPANT_VERIFICATION_TOKEN_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ParticipantRecord, EventRecord> PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY = ForeignKeys0.PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ContactRecord, Long> IDENTITY_CONTACT = Internal.createIdentity(Contact.CONTACT, Contact.CONTACT.ID);
        public static Identity<EventRecord, Long> IDENTITY_EVENT = Internal.createIdentity(Event.EVENT, Event.EVENT.ID);
        public static Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = Internal.createIdentity(Participant.PARTICIPANT, Participant.PARTICIPANT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ContactRecord> CONTACT_PKEY = Internal.createUniqueKey(Contact.CONTACT, "contact_pkey", Contact.CONTACT.ID);
        public static final UniqueKey<ContactRecord> CONTACT_EMAIL_KEY = Internal.createUniqueKey(Contact.CONTACT, "contact_email_key", Contact.CONTACT.EMAIL);
        public static final UniqueKey<EventRecord> EVENT_PKEY = Internal.createUniqueKey(Event.EVENT, "event_pkey", Event.EVENT.ID);
        public static final UniqueKey<EventRecord> EVENT_VOLUME_KEY = Internal.createUniqueKey(Event.EVENT, "event_volume_key", Event.EVENT.VOLUME);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = Internal.createUniqueKey(Participant.PARTICIPANT, "participant_pkey", Participant.PARTICIPANT.ID);
        public static final UniqueKey<ParticipantRecord> PARTICIPANT_VERIFICATION_TOKEN_UNIQUE = Internal.createUniqueKey(Participant.PARTICIPANT, "participant_verification_token_unique", Participant.PARTICIPANT.VERIFICATION_TOKEN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ParticipantRecord, EventRecord> PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY = Internal.createForeignKey(meta.Keys.EVENT_PKEY, Participant.PARTICIPANT, "participant__participant_event_id_fkey", Participant.PARTICIPANT.EVENT_ID);
    }
}
