/*
 * This file is generated by jOOQ.
 */
package meta;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import meta.tables.Contact;
import meta.tables.Event;
import meta.tables.FlywaySchemaHistory;
import meta.tables.Participant;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1155042656;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.contact</code>.
     */
    public final Contact CONTACT = meta.tables.Contact.CONTACT;

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = meta.tables.Event.EVENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = meta.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.participant</code>.
     */
    public final Participant PARTICIPANT = meta.tables.Participant.PARTICIPANT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CONTACT_ID_SEQ,
            Sequences.EVENT_ID_SEQ,
            Sequences.PARTICIPANT_EVENT_ID_SEQ,
            Sequences.PARTICIPANT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Contact.CONTACT,
            Event.EVENT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Participant.PARTICIPANT);
    }
}
