/*
 * This file is generated by jOOQ.
 */
package meta;


import javax.annotation.processing.Generated;

import meta.routines.UpdateEventStatus;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.update_event_status</code>
     */
    public static void updateEventStatus(Configuration configuration) {
        UpdateEventStatus p = new UpdateEventStatus();

        p.execute(configuration);
    }
}
