/*
 * This file is generated by jOOQ.
*/
package meta;


import javax.annotation.Generated;

import meta.routines.AddContact;
import meta.routines.CheckIfMaxParticipantsChanged;
import meta.routines.EventStatusPossiblyChanges;
import meta.routines.UpdateEventStatus;
import meta.routines.UpdateTimestamp;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Object addContact(Configuration configuration) {
        AddContact f = new AddContact();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Field<Object> addContact() {
        AddContact f = new AddContact();

        return f.asField();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Object checkIfMaxParticipantsChanged(Configuration configuration) {
        CheckIfMaxParticipantsChanged f = new CheckIfMaxParticipantsChanged();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Field<Object> checkIfMaxParticipantsChanged() {
        CheckIfMaxParticipantsChanged f = new CheckIfMaxParticipantsChanged();

        return f.asField();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Object eventStatusPossiblyChanges(Configuration configuration) {
        EventStatusPossiblyChanges f = new EventStatusPossiblyChanges();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Field<Object> eventStatusPossiblyChanges() {
        EventStatusPossiblyChanges f = new EventStatusPossiblyChanges();

        return f.asField();
    }

    /**
     * Call <code>public.update_event_status</code>
     */
    public static void updateEventStatus(Configuration configuration) {
        UpdateEventStatus p = new UpdateEventStatus();

        p.execute(configuration);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Object updateTimestamp(Configuration configuration) {
        UpdateTimestamp f = new UpdateTimestamp();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public static Field<Object> updateTimestamp() {
        UpdateTimestamp f = new UpdateTimestamp();

        return f.asField();
    }
}
