/*
 * This file is generated by jOOQ.
 */
package meta;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.contact_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_ID_SEQ = new SequenceImpl<Long>("contact_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.event_id_seq</code>
     */
    public static final Sequence<Long> EVENT_ID_SEQ = new SequenceImpl<Long>("event_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.participant_event_id_seq</code>
     */
    public static final Sequence<Long> PARTICIPANT_EVENT_ID_SEQ = new SequenceImpl<Long>("participant_event_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.participant_id_seq</code>
     */
    public static final Sequence<Long> PARTICIPANT_ID_SEQ = new SequenceImpl<Long>("participant_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
