/*
 * This file is generated by jOOQ.
 */
package meta;


import javax.annotation.processing.Generated;

import meta.tables.Contact;
import meta.tables.Event;
import meta.tables.FlywaySchemaHistory;
import meta.tables.Participant;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.contact</code>.
     */
    public static final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>public.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.participant</code>.
     */
    public static final Participant PARTICIPANT = Participant.PARTICIPANT;
}
