/*
 * This file is generated by jOOQ.
 */
package meta.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import meta.Indexes;
import meta.Keys;
import meta.Public;
import meta.enums.ParticipantStatus;
import meta.tables.records.ParticipantRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participant extends TableImpl<ParticipantRecord> {

    private static final long serialVersionUID = -311980109;

    /**
     * The reference instance of <code>public.participant</code>
     */
    public static final Participant PARTICIPANT = new Participant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParticipantRecord> getRecordType() {
        return ParticipantRecord.class;
    }

    /**
     * The column <code>public.participant.id</code>.
     */
    public final TableField<ParticipantRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('participant_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.participant.first_name</code>.
     */
    public final TableField<ParticipantRecord, String> FIRST_NAME = createField(DSL.name("first_name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.participant.last_name</code>.
     */
    public final TableField<ParticipantRecord, String> LAST_NAME = createField(DSL.name("last_name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.participant.email</code>.
     */
    public final TableField<ParticipantRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.participant.affiliation</code>.
     */
    public final TableField<ParticipantRecord, String> AFFILIATION = createField(DSL.name("affiliation"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.participant.verification_token</code>.
     */
    public final TableField<ParticipantRecord, String> VERIFICATION_TOKEN = createField(DSL.name("verification_token"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.participant.order_number</code>.
     */
    public final TableField<ParticipantRecord, Integer> ORDER_NUMBER = createField(DSL.name("order_number"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.participant.event_id</code>.
     */
    public final TableField<ParticipantRecord, Long> EVENT_ID = createField(DSL.name("event_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('participant_event_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.participant.status</code>.
     */
    public final TableField<ParticipantRecord, ParticipantStatus> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(meta.enums.ParticipantStatus.class), this, "");

    /**
     * The column <code>public.participant.created_on</code>.
     */
    public final TableField<ParticipantRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>public.participant.updated_on</code>.
     */
    public final TableField<ParticipantRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>public.participant</code> table reference
     */
    public Participant() {
        this(DSL.name("participant"), null);
    }

    /**
     * Create an aliased <code>public.participant</code> table reference
     */
    public Participant(String alias) {
        this(DSL.name(alias), PARTICIPANT);
    }

    /**
     * Create an aliased <code>public.participant</code> table reference
     */
    public Participant(Name alias) {
        this(alias, PARTICIPANT);
    }

    private Participant(Name alias, Table<ParticipantRecord> aliased) {
        this(alias, aliased, null);
    }

    private Participant(Name alias, Table<ParticipantRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Participant(Table<O> child, ForeignKey<O, ParticipantRecord> key) {
        super(child, key, PARTICIPANT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARTICIPANT_PKEY, Indexes.PARTICIPANT_VERIFICATION_TOKEN_UNIQUE);
    }

    @Override
    public Identity<ParticipantRecord, Long> getIdentity() {
        return Keys.IDENTITY_PARTICIPANT;
    }

    @Override
    public UniqueKey<ParticipantRecord> getPrimaryKey() {
        return Keys.PARTICIPANT_PKEY;
    }

    @Override
    public List<UniqueKey<ParticipantRecord>> getKeys() {
        return Arrays.<UniqueKey<ParticipantRecord>>asList(Keys.PARTICIPANT_PKEY, Keys.PARTICIPANT_VERIFICATION_TOKEN_UNIQUE);
    }

    @Override
    public List<ForeignKey<ParticipantRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ParticipantRecord, ?>>asList(Keys.PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY);
    }

    public Event event() {
        return new Event(this, Keys.PARTICIPANT__PARTICIPANT_EVENT_ID_FKEY);
    }

    @Override
    public Participant as(String alias) {
        return new Participant(DSL.name(alias), this);
    }

    @Override
    public Participant as(Name alias) {
        return new Participant(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Participant rename(String name) {
        return new Participant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Participant rename(Name name) {
        return new Participant(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, String, Integer, Long, ParticipantStatus, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
