/*
 * This file is generated by jOOQ.
*/
package meta.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import meta.enums.ParticipantStatus;
import meta.tables.Participant;
import meta.tables.records.ParticipantRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantDao extends DAOImpl<ParticipantRecord, meta.tables.pojos.Participant, Long> {

    /**
     * Create a new ParticipantDao without any configuration
     */
    public ParticipantDao() {
        super(Participant.PARTICIPANT, meta.tables.pojos.Participant.class);
    }

    /**
     * Create a new ParticipantDao with an attached configuration
     */
    public ParticipantDao(Configuration configuration) {
        super(Participant.PARTICIPANT, meta.tables.pojos.Participant.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(meta.tables.pojos.Participant object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchById(Long... values) {
        return fetch(Participant.PARTICIPANT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public meta.tables.pojos.Participant fetchOneById(Long value) {
        return fetchOne(Participant.PARTICIPANT.ID, value);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByFirstName(String... values) {
        return fetch(Participant.PARTICIPANT.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByLastName(String... values) {
        return fetch(Participant.PARTICIPANT.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByEmail(String... values) {
        return fetch(Participant.PARTICIPANT.EMAIL, values);
    }

    /**
     * Fetch records that have <code>affiliation IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByAffiliation(String... values) {
        return fetch(Participant.PARTICIPANT.AFFILIATION, values);
    }

    /**
     * Fetch records that have <code>verification_token IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByVerificationToken(String... values) {
        return fetch(Participant.PARTICIPANT.VERIFICATION_TOKEN, values);
    }

    /**
     * Fetch records that have <code>order_number IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByOrderNumber(Integer... values) {
        return fetch(Participant.PARTICIPANT.ORDER_NUMBER, values);
    }

    /**
     * Fetch records that have <code>event_id IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByEventId(Long... values) {
        return fetch(Participant.PARTICIPANT.EVENT_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByStatus(ParticipantStatus... values) {
        return fetch(Participant.PARTICIPANT.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByCreatedOn(Timestamp... values) {
        return fetch(Participant.PARTICIPANT.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<meta.tables.pojos.Participant> fetchByUpdatedOn(Timestamp... values) {
        return fetch(Participant.PARTICIPANT.UPDATED_ON, values);
    }
}
