/*
 * This file is generated by jOOQ.
*/
package meta.tables.records;


import javax.annotation.Generated;

import meta.tables.EmailBlacklist;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailBlacklistRecord extends UpdatableRecordImpl<EmailBlacklistRecord> implements Record1<String> {

    private static final long serialVersionUID = 1178610406;

    /**
     * Setter for <code>public.email_blacklist.email</code>.
     */
    public EmailBlacklistRecord setEmail(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.email_blacklist.email</code>.
     */
    public String getEmail() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return EmailBlacklist.EMAIL_BLACKLIST.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailBlacklistRecord value1(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailBlacklistRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailBlacklistRecord
     */
    public EmailBlacklistRecord() {
        super(EmailBlacklist.EMAIL_BLACKLIST);
    }

    /**
     * Create a detached, initialised EmailBlacklistRecord
     */
    public EmailBlacklistRecord(String email) {
        super(EmailBlacklist.EMAIL_BLACKLIST);

        set(0, email);
    }
}
