/*
 * This file is generated by jOOQ.
*/
package meta.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.enums.ParticipantStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IParticipant extends Serializable {

    /**
     * Getter for <code>public.participant.id</code>.
     */
    public Long getId();

    /**
     * Getter for <code>public.participant.first_name</code>.
     */
    public String getFirstName();

    /**
     * Getter for <code>public.participant.last_name</code>.
     */
    public String getLastName();

    /**
     * Getter for <code>public.participant.email</code>.
     */
    public String getEmail();

    /**
     * Getter for <code>public.participant.affiliation</code>.
     */
    public String getAffiliation();

    /**
     * Getter for <code>public.participant.verification_token</code>.
     */
    public String getVerificationToken();

    /**
     * Getter for <code>public.participant.order_number</code>.
     */
    public Integer getOrderNumber();

    /**
     * Getter for <code>public.participant.event_id</code>.
     */
    public Long getEventId();

    /**
     * Getter for <code>public.participant.status</code>.
     */
    public ParticipantStatus getStatus();

    /**
     * Getter for <code>public.participant.created_on</code>.
     */
    public Timestamp getCreatedOn();

    /**
     * Getter for <code>public.participant.updated_on</code>.
     */
    public Timestamp getUpdatedOn();
}
