name: Deploy staging

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build . --tag wds-backend:$(git rev-parse --short "$GITHUB_SHA")
      working-directory: packages/wds-event-tool
