name: Deploy

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      WORKSPACE: ${GITHUB_REF##*/}
    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build . --tag registry.fly.io/wds-backend-$WORKSPACE:$(git rev-parse --short "$GITHUB_SHA")
      working-directory: packages/wds-event-tool
    - name: Install flyctl
      run: sudo curl -L https://fly.io/install.sh | sh
    - name: Authenticate docker to push to fly.io
      run: /home/runner/.fly/bin/flyctl auth docker
    - name: Push docker image
      run: docker push registry.fly.io/wds-backend-$WORKSPACE:$(git rev-parse --short "$GITHUB_SHA")
    - name: Apply new image to fly machine
      run: /home/runner/.fly/bin/flyctl image update --image registry.fly.io/wds-backend-$WORKSPACE:$(git rev-parse --short "$GITHUB_SHA") --app wds-backend-$WORKSPACE
    
