name: Deploy

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      WORKSPACE: ${{ github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the image
      run: docker build . --tag registry.fly.io/wds-backend-$WORKSPACE:$COMMIT_SHA
      working-directory: packages/wds-event-tool
    - name: Install flyctl
      run: sudo curl -L https://fly.io/install.sh | sh
    - name: Authenticate docker to push to fly.io
      run: /home/runner/.fly/bin/flyctl auth docker
    - name: Push docker image
      run: docker push registry.fly.io/wds-backend-$WORKSPACE:$COMMIT_SHA
    - name: Set machine id to env
      run: |
          echo "MACHINE_ID=$(/home/runner/.fly/bin/flyctl machine list --app wds-backend-$WORKSPACE --json | jq '[.[]|.id][0]')"  >> $GITHUB_ENV
    - name: Apply new image to fly machine
      run: /home/runner/.fly/bin/flyctl machine update ${{ env.MACHINE_ID }} --image registry.fly.io/wds-backend-$WORKSPACE:$COMMIT_SHA --app wds-backend-$WORKSPACE -y
    - name: Restart the machine
      run: /home/runner/.fly/bin/flyctl machine restart ${{ env.MACHINE_ID }} --app wds-backend-$WORKSPACE
