name: Verify

on:
  pull_request:
    branches: [ "staging", "master" ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/wds-event-tool
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      WORKSPACE: ${{ github.ref_name == 'master' && 'prod' || github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      FIREBASE_SERVICEACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICEACCOUNT_KEY }}
      SECRETS_YAML: ${{ secrets.SECRETS_YAML }}
    steps:
      - uses: actions/checkout@v3
      - name: Run postgres db for testing
        run: |
          docker run --rm --name test_db -d postgres:10.6
          timeout 90s sh -c "until docker exec test_db pg_isready ; do sleep 5 ; done"
      - name: Build app container for testing
        run: |
          mkdir ./build
          docker build --target=build --build-arg SECRETS_YAML="$SECRETS_YAML" --build-arg FIREBASE_SERVICEACCOUNT_KEY="$FIREBASE_SERVICEACCOUNT_KEY" . --tag wds-backend-test-$WORKSPACE:$COMMIT_SHA
      - name: Run tests
        run: |
          docker run --entrypoint=gradle -v $PWD/build:/home/gradle/project/build --env DB_URL=jdbc:postgresql://test_db:5432/wds_db wds-backend-test-$WORKSPACE:$COMMIT_SHA test -i -x jooq-codegen-meta
      - name: Check files in folders
        run: |
          ls -la
          ls -la $pwd/build/test-results/test
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: JUNIT Tests
          path: ./build/test-results/test/*.xml
          reporter: java-junit
