name: Verify

on:
  pull_request:
    branches: [ "staging", "master" ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/wds-event-tool
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      WORKSPACE: ${{ github.ref_name == 'master' && 'prod' || github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      FIREBASE_SERVICEACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICEACCOUNT_KEY }}
      SECRETS_YAML: ${{ secrets.SECRETS_YAML }}
    steps:
      - uses: actions/checkout@v3
      - name: Run postgres db for testing
        run: |
          docker run --rm --name test_db -d postgres:10.6
          timeout 90s sh -c "until docker exec test_db pg_isready ; do sleep 5 ; done"
      - name: Build app container for testing
        run: |
          docker build --target=build --build-arg SECRETS_YAML="$SECRETS_YAML" --build-arg FIREBASE_SERVICEACCOUNT_KEY="$FIREBASE_SERVICEACCOUNT_KEY" . --tag wds-backend-test
      - name: Run tests
        run: |
          docker run --rm --name wds-backend-test --entrypoint=tail -d --env DB_URL=jdbc:postgresql://test_db:5432/wds_db wds-backend-test -f > /dev/null
          docker exec wds-backend-test gradle test -x jooq-codegen-meta
          docker cp wds-backend-test:"/home/gradle/project/build/test-results/test/." "./test-results/"
      - name: Check files in test-results
        run: ls -la ./test-results
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: JUNIT Tests
          path: test-results/*.xml
          reporter: java-junit
